
#################### USERS ####################

#### Registrando usuário
POST https://desafio-node-south.herokuapp.com/users/register
Content-Type: application/json

{
  "email": "client2@user.com",
  "password": "123",
  "role": "client"
}

#### Logando usuário
POST https://desafio-node-south.herokuapp.com/users/login
Content-Type: application/json

# "email": "client@user.com",
{
  "email": "admin@user.com",
  "password": "123"
}


#################### PRODUCTS ####################

#### Lista de todos os produtos
GET https://desafio-node-south.herokuapp.com/products
# GET https://desafio-node-south.herokuapp.com/products?page=3&limit=10&name=&available=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTg3NDdmZjZlYjY1MDQ5YzE0NTc3NSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE2MDQ5MzYxNTYsImV4cCI6MTYwNDkzOTc1Nn0.IBlE_zF4l6Tqz_LuWwrJXxsKs_YGYshk8Xlqs04P-1A

#### Criando um produto
POST https://desafio-node-south.herokuapp.com/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTg3NDdmZjZlYjY1MDQ5YzE0NTc3NSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE2MDQ4OTA0NzIsImV4cCI6MTYwNDg5NDA3Mn0.ZKwRUTxFYHjGqw3wrGntQ0HzZN7MCoWbo-3OhVNidDI

{
  "name": "Produto 14",
  "price": 99.99,
  "quantity": 0
}


#### Buscando um produto por id
GET https://desafio-node-south.herokuapp.com/products/5fa75a83b02b2702242bb10a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTc4ZWIzYzVjYTllMTY4MGU3MjM3MCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYwNDgyMDUwOCwiZXhwIjoxNjA0ODI0MTA4fQ.EhvfFgPzdYtDYeaDth0gcKa3IQm7Mc8Pf7W3gdPig8A


#### Atualizando um produto por id
PATCH https://desafio-node-south.herokuapp.com/products/5fa79ae94d87ac2780291a80
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTdhMjYwY2JhMTFjNGFiODk1ODNkYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYwNDg3NDU3NSwiZXhwIjoxNjA0ODc4MTc1fQ.DJPU7EtzJljdxj_nNlgVgiTTSin0c-jHdCDJeXXDzwY

{
  "name": "Produto 1",
  "price": 99.99,
  "quantity": 3
}


#### Excluindo um produto por id
DELETE https://desafio-node-south.herokuapp.com/products/5fa75a83b02b2702242bb10a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTc4ZWIzYzVjYTllMTY4MGU3MjM3MCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYwNDgyMDUwOCwiZXhwIjoxNjA0ODI0MTA4fQ.EhvfFgPzdYtDYeaDth0gcKa3IQm7Mc8Pf7W3gdPig8A


#### 404 / Rota não encontrada
GET https://desafio-node-south.herokuapp.com/5fa606c051a7062aa8ec2e9d
